### ISSUE TITLE
In case of failure in contacting CommonStorage

### ISSUE THREAD

**Issue by shimoncohen** [MapColonies/exporter-trigger#43]
When contacting CommonStorage, should we address the situation in which we fail to create a row in CommonStorage?

In case we want to address this issue, we may save the "lost" exports and try to send them when possible. In this case, we should check if they aren't already present (ExporterTrigger started working on them).

**Comment by ssharon-rnd** [comment]
@shimoncohen are you using kaffka? if so why not return the msg to the queue?

**Comment by shimoncohen** [comment]
I was referring to the situation in which we were able to send a message to kafka, so the worker will work on the export. But, we fail to save the data to the CommonStorage. In this case we "lose" the sizeEst, tilesEst, creationDate and bbox data, because the ExporterTrigger failed to create the document.

**Comment by asafMasa** [comment]
As described in the design review:
- if storage failed in trigger (creating the record) the trigger will return error response to the client
- if storage failed in worker the file will be created but **no record will suggest it's existence or its URI** which is a problem
