### ISSUE TITLE
add ci to exporter services

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/exporter-trigger#68]
- [x] client - https://github.com/MapColonies/image-exporter-client
- [x] trigger - https://github.com/MapColonies/exporter-trigger
- [x] worker - https://github.com/MapColonies/exporter-worker
- [x] export storage - https://github.com/MapColonies/export-request-storage

optional
- [x] common-storage - https://github.com/MapColonies/CommonStorage

**Comment by yossiz16** [comment]
exporter trigger and exporter-worker - done including docker build and push(not active)
image-exporter-client - waiting to fix to the test issue 
export-request-storage - done  require some code and lint fixes 
common-storage - done  require some code and lint fixes
